#!/bin/bash -e

git_repo=https://github.com/dev-sec/ansible-os-hardening.git
ansible_role=os_hardening

# checkout
workdir=$(mktemp -d)
pushd $workdir > /dev/null
git clone $git_repo
cd ansible-os-hardening

# install dependencies
ansible-galaxy collection install devsec.hardening

# create playbook
cat << END > hardening.yaml
- hosts: localhost
  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.os_hardening
END

# call the play
ansible-playbook hardening.yaml

# hit the showers
popd; rm -rf $workdir

