#!/bin/bash -e
PATH=/bin:/usr/bin:/sbin:/usr/sbin
umask 22

[ -f /etc/os-release ] && source /etc/os-release

jq_download_url="https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64"

# ------------------------------
# yum blacklist
# ------------------------------
yum -y erase \
  ghostscript \
  2> /dev/null

# ------------------------------
# update before new installs
# ------------------------------
yum -y update

# ------------------------------
# release-specific items
# ------------------------------
case "$NAME" in 

  *Amazon*)
    yum -y install amazon-ssm-agent && systemctl enable amazon-ssm-agent
    ;;
    
  *Centos*)
    ;;
    
esac

# ------------------------------
# common RPM packages
# ------------------------------
yum -y install \
  ansible \
  bind-utils \
  binutils \
  coreutils  \
  curl \
  git \
  mlocate \
  net-tools \
  postfix \
  python3 \
  screen \
  unzip \
  vim \
  unzip \
  zip \
  zsh

# ------------------------------
# changing some defaults
# ------------------------------
alternatives --install /usr/bin/python python /usr/bin/python2 50
alternatives --install /usr/bin/python python /usr/bin/python3 90


# ------------------------------
# non-RPM base packages
# ------------------------------

# jq
curl -skL "$jq_download_url" -o /usr/bin/jq && \
chown root:root /usr/bin/jq && \
chmod 755 /usr/bin/jq || true
