#!/bin/bash -e

[ -f /etc/os-release ] && source /etc/os-release

case "$NAME" in

  *Amazon*)
    amazon-linux-extras install -y epel
    amazon-linux-extras enable epel
    ;;

  *Red?Hat*)
    yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    ;;

  *CentOS*)
    yum -y install epel-release
    ;;

esac
