#!/bin/bash -e

[ -f /etc/os-release ] && source /etc/os-release 

case "$NAME" in 

  *Amazon*)
    amazon-linux-extras install -y epel
    amazon-linux-extras enable epel
    ;;
    
  *Centos*)
    yum -y install epel-release
    ;;
    
esac
