- hosts: localhost
  gather_facts: false
  vars_files:
    - vars/main.yaml
    - vars/endpoints.yaml
    - vars/vault.yaml

  tasks:

    - name: "create endpoint artifacts dirs"
      file: path={{endpoint_artifact_dir}}/{{item.0}}/{{item.1}} state=directory
      with_nested:
        - "{{domains}}"
        - [ "CSRs", "certs/internal", "certs/external", "keys" ]

    - name: generate endpoint private key
      community.crypto.openssl_privatekey:
        path: "{{endpoint_artifact_dir}}/{{item.1}}/keys/{{item.0.name}}.{{item.1}}.pem"
        passphrase: "{{endpoint_key_passphrase}}"
        cipher: auto
      with_nested:
        - "{{endpoints}}"
        - "{{domains}}"

    - name: generate endpoint CSR
      community.crypto.openssl_csr:
        path: "{{endpoint_artifact_dir}}/{{item.1}}/CSRs/{{item.0.name}}.{{item.1}}.pem"
        privatekey_path: "{{endpoint_artifact_dir}}/{{item.1}}/keys/{{item.0.name}}.{{item.1}}.pem"
        privatekey_passphrase: "{{endpoint_key_passphrase}}"
        common_name: "{{item.0.name}}.{{item.1}}"
        subject_alt_name: "{{ (item.0.sans is defined) | ternary(_sans_standard + _sans_custom, _sans_standard) }}"
      with_nested:
        - "{{endpoints}}"
        - "{{domains}}"
      vars:
        _sans_standard:
          - "DNS:{{ item.0.name }}.{{ item.1 }}"
          - "DNS:{{ item.0.name }}"
          - "DNS:localhost"
          - "IP:127.0.0.1"
        _sans_custom:
          - "{{ item.0.sans | default([]) | join(',') | replace(',', '.' + item.1 + ', ') + '.' + item.1 }}"
          - "{{ item.0.sans | default([]) | join(',') }}"

    - name: generate endpoint cert
      community.crypto.x509_certificate:
        path: "{{endpoint_artifact_dir}}/{{item.1}}/certs/internal/{{item.0.name}}.{{item.1}}.pem"
        csr_path: "{{endpoint_artifact_dir}}/{{item.1}}/CSRs/{{item.0.name}}.{{item.1}}.pem"
        ownca_path: "{{ca_artifact_dir}}/certs/demo-ca-int1.pem"
        ownca_privatekey_path: "{{ca_artifact_dir}}/keys/demo-ca-int1.pem"
        ownca_privatekey_passphrase: "{{ca_key_passphrase}}"
        provider: ownca
      with_nested:
        - "{{endpoints}}"
        - "{{domains}}"


