#!/bin/bash -e

buildops="$*"

v=$(date '+%Y%m%d') \
&& docker build $buildops --label version=$v -t techtribeone/ubi9-core:latest -t techtribeone/ubi9-core:$v -f techtribeone-core.dockerfile . \
&& docker build $buildops --label version=$v -t techtribeone/ubi9-cli:latest -t techtribeone/ubi9-cli:$v -f techtribeone-cli.dockerfile . \
&& docker build $buildops --label version=$v -t techtribeone/ubi9-iac:latest -t techtribeone/ubi9-iac:$v -f techtribeone-iac.dockerfile . \

