---
es_version: '6.8.17'
es_version_lock: true
es_add_repository: false
es_use_repository: true
es_api_host: '0.0.0.0'
es_api_scheme: http
es_heap_size: 1g
es_logs_dir: /var/log/elasticsearch

es_data_dirs:
  - /data1/myorg/elasticsearch
  - /data2/myorg/elasticsearch
  - /data3/myorg/elasticsearch
  - /data4/myorg/elasticsearch
  - /data5/myorg/elasticsearch

es_config:
  cluster.name: myorg
  discovery.zen.ping.unicast.hosts:
    - myorg-es01
    - myorg-es02
    - myorg-es03
  indices.lifecycle.poll_interval: 30s
  network.host: 0.0.0.0
  node.name: '{{inventory_hostname}}'
  cluster.routing.allocation.disk.watermark.low: 3gb
  cluster.routing.allocation.disk.watermark.high: 3gb
  cluster.routing.allocation.disk.watermark.flood_stage: 3gb
  cluster.info.update.interval: 1m
  xpack.license.self_generated.type: basic
