- name: add repository
  ansible.builtin.yum_repository:
    name: "site"
    description: "site"
    baseurl: "{{site_repo_yum_baseurl}}"
    keepalive: yes
# - name: test file backup
#   become: yes
#   ansible.builtin.template:
#     src: elasticsearch.yml.j2
#     dest: "/etc/elasticsearch/elasticsearch.yml"
#     owner: root
#     group: "elasticsearch"
#     mode: "660"
#     force: yes
#     backup: yes
#   register: system_change
#   notify: restart elasticsearch
