# ------------------------------------------------------------
# generic stuff
# ------------------------------------------------------------
site_repo_yum_baseurl: file:///var/repo/yum

# ------------------------------------------------------------
# elasticsearch
# ------------------------------------------------------------
es_server_nodes:
  - myorg-es01:9200
  - myorg-es02:9200
  - myorg-es03:9200

# ------------------------------------------------------------
# elastic beats
# ------------------------------------------------------------
beats_add_repository: false

filebeat_beats_version: '6.8.17'
filebeat_version_lock: true
filebeat_allow_downgrade: true

metricbeat_beats_version: '6.8.17'
metricbeat_version_lock: true
metricbeat_allow_downgrade: true
metricbeat_kibana_host: myorg-es01:5601
