apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: conleys
spec:
  nodeName: i-0331dfeb96d4a1c07-minion
  containers:
  - name: alpine
    image: 769788309369.dkr.ecr.us-gov-west-1.amazonaws.com/csde/apps/alpine:3.11.6
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
