apiVersion: v1
kind: Pod
metadata:
  name: bbox
  namespace: conleys
spec:
  nodeName: i-00027076c90020293-minion
  containers:
  - name: bbox
    image: 769788309369.dkr.ecr.us-gov-west-1.amazonaws.com/csde/apps/busybox:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
