#!/bin/bash -e

buildops="$*"

v=$(date '+%Y%m%d') \
&& docker build $buildops --label version=$v -t techtribeone/centos7-core:latest -t techtribeone/centos7-core:$v -f techtribeone-core.dockerfile . \
&& docker build $buildops --label version=$v -t techtribeone/centos7-cli:latest -t techtribeone/centos7-cli:$v -f techtribeone-cli.dockerfile . \
&& docker build $buildops --label version=$v -t techtribeone/centos7-iac:latest -t techtribeone/centos7-iac:$v -f techtribeone-iac.dockerfile . \

