#!/bin/bash -e

buildops="$*"

v=$(date '+%Y%m%d') \
&& docker build $buildops --label version=$v -t techtribeone/ubi8-core:latest -t techtribeone/ubi8-core:$v -f techtribeone-core.dockerfile . \
&& docker build $buildops --label version=$v -t techtribeone/ubi8-cli:latest -t techtribeone/ubi8-cli:$v -f techtribeone-cli.dockerfile . \
&& docker build $buildops --label version=$v -t techtribeone/ubi8-iac:latest -t techtribeone/ubi8-iac:$v -f techtribeone-iac.dockerfile . \

